package ttknpdev.gui.tabel_read;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JTable;
import ttknpdev.entity.Toy;
import ttknpdev.entity.ToyTableModel;
import ttknpdev.gui.frame.MyFrame;
import ttknpdev.service.ToyService;

public class ShowToy extends javax.swing.JPanel implements ActionListener {


   private MyFrame frame;
   private Toy toy;
   private ToyTableModel toyTableModel;
   private JTable jTableToy;
   private ToyService toyService;

   public ShowToy() {
      // 0rder it's improtance
      initComponents();
      frame = new MyFrame("READ");
      frame.setSize(500, 310);
      frame.setDefaultCloseOperation(frame.DISPOSE_ON_CLOSE);
      toyService = new ToyService(); // inject it
      jTableToy = new JTable();
      toyTableModel = new ToyTableModel();
      /* i need to show jtable before click */
      jTableToy.setModel(toyTableModel);
      jScrollPane.getViewport().add(jTableToy);
   }

   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code.
    * The content of this method is always regenerated by
    * the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabelPutId = new javax.swing.JLabel();
      jTextFieldToyId = new javax.swing.JTextField();
      jScrollPane = new javax.swing.JScrollPane();
      jButtonSearch = new javax.swing.JButton();

      jLabelPutId.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
      jLabelPutId.setText("Put the toy id");

      jTextFieldToyId.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
      jTextFieldToyId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

      jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
      jButtonSearch.setText("search");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jScrollPane))
               .addGroup(layout.createSequentialGroup()
                  .addGap(137, 137, 137)
                  .addComponent(jLabelPutId)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jTextFieldToyId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 130, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(191, 191, 191))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelPutId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jTextFieldToyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addGap(26, 26, 26))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonSearch;
   private javax.swing.JLabel jLabelPutId;
   private javax.swing.JScrollPane jScrollPane;
   private javax.swing.JTextField jTextFieldToyId;
   // End of variables declaration//GEN-END:variables

   public void display() {

      frame.setContentPane(this); // add panel
      frame.setVisible(true);
      
      jButtonSearch.addActionListener(this);
      
      /* way to do some thing when close frame  */
      frame.addWindowListener(new WindowAdapter() {
         @Override
         public void windowClosing(WindowEvent e) {
            System.out.println("closing to use this frame and connect database");
            toyService.closeConnect();
         }
      });
      
   }

   @Override
   public void actionPerformed(ActionEvent e) {

      // connect and query 
      toy = toyService.read(Long.valueOf(jTextFieldToyId.getText())); // get toy by id
      toyTableModel.setToy(toy);
      jTableToy.setModel(toyTableModel);
      jScrollPane.getViewport().add(jTableToy);

   }

}
