package ttknpdev.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import ttknpdev.gui.form_create.FormCreate;
import ttknpdev.gui.form_update.FormUpdate;
import ttknpdev.gui.frame.MyFrame;
import ttknpdev.gui.tabel_read.ShowToy;
import ttknpdev.gui.tabel_reads.ShowToys;


public class ChooseFrames extends javax.swing.JPanel implements ActionListener {

   /**
    * Creates new form ChooseFrames
    */
   private MyFrame frame;
   private ShowToys showToys;
   private ShowToy showToy;
   private FormCreate formCreate;
   private FormUpdate formUpdate;

   public ChooseFrames() {
      initComponents();
      frame = new MyFrame("Title");
      frame.setSize(500, 310);
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   }

   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code.
    * The content of this method is always regenerated by
    * the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabelTitle = new javax.swing.JLabel();
      jButtonReads = new javax.swing.JButton();
      jButtonRead = new javax.swing.JButton();
      jButtonCreate = new javax.swing.JButton();
      jButtonUpdate = new javax.swing.JButton();

      jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
      jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabelTitle.setText("Java Swing GUI Crud");

      jButtonReads.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jButtonReads.setText("Reads");

      jButtonRead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jButtonRead.setText("Read");

      jButtonCreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jButtonCreate.setText("Create");

      jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jButtonUpdate.setText("Update");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(111, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButtonReads, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(50, 50, 50)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonRead, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(113, 113, 113))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jLabelTitle)
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonReads, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonRead, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(34, 34, 34)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(55, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonCreate;
   private javax.swing.JButton jButtonRead;
   private javax.swing.JButton jButtonReads;
   private javax.swing.JButton jButtonUpdate;
   private javax.swing.JLabel jLabelTitle;
   // End of variables declaration//GEN-END:variables

   public void display() {
      frame.setContentPane(this);
      frame.setVisible(true);
      jButtonReads.addActionListener(this);
      jButtonRead.addActionListener(this);
      jButtonCreate.addActionListener(this);
      jButtonUpdate.addActionListener(this);
      
   }

   @Override
   public void actionPerformed(ActionEvent e) {
      // System.out.println(e.getActionCommand()); // returns action commamnd
      if (e.getActionCommand().equals("Reads")) {
         showToys = new ShowToys();
         showToys.display();
      } else if (e.getActionCommand().equals("Read")) {
         showToy = new ShowToy();
         showToy.display();
      } else if (e.getActionCommand().equals("Create")) {
         formCreate = new FormCreate();
         formCreate.display();
      } else if (e.getActionCommand().equals("Update")) {
         formUpdate = new FormUpdate();
         formUpdate.display();
      }
   }

}
