package ttknpdev.gui.form_update;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ttknpdev.entity.Toy;
import ttknpdev.enums.Status;
import ttknpdev.gui.frame.MyFrame;
import ttknpdev.service.ToyService;


public class FormUpdate extends javax.swing.JPanel implements ActionListener {

   private MyFrame frame;
   private ToyService toyService;
   private ButtonGroup buttonGroupStatus;
   private Toy toy;

   public FormUpdate() {
      initComponents();
      frame = new MyFrame("UPDATE");
      frame.setSize(500, 330);
      frame.setDefaultCloseOperation(frame.DISPOSE_ON_CLOSE);
      buttonGroupStatus = new ButtonGroup();
      buttonGroupStatus.add(jRadioButtonUnused);
      buttonGroupStatus.add(jRadioButtonUse);
      toyService = new ToyService();
   }

   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code.
    * The content of this method is always regenerated by
    * the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabelTitle = new javax.swing.JLabel();
      jLabelPutId = new javax.swing.JLabel();
      jTextFieldToyId = new javax.swing.JTextField();
      jLabelProductName = new javax.swing.JLabel();
      jTextFieldProductName = new javax.swing.JTextField();
      jLabelProductPrice = new javax.swing.JLabel();
      jTextFieldProductPrice = new javax.swing.JTextField();
      jLabelUnit = new javax.swing.JLabel();
      jRadioButtonUnused = new javax.swing.JRadioButton();
      jRadioButtonUse = new javax.swing.JRadioButton();
      jButtonUpdate = new javax.swing.JButton();
      jButtonSearch = new javax.swing.JButton();

      jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
      jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabelTitle.setText("Form update toy");

      jLabelPutId.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
      jLabelPutId.setText("Search by toy id");

      jTextFieldToyId.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
      jTextFieldToyId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      jTextFieldToyId.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldToyIdActionPerformed(evt);
         }
      });

      jLabelProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabelProductName.setText("Product name");

      jTextFieldProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jTextFieldProductName.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldProductNameActionPerformed(evt);
         }
      });

      jLabelProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabelProductPrice.setText("Product price");

      jTextFieldProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

      jLabelUnit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jLabelUnit.setText("฿");

      jRadioButtonUnused.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jRadioButtonUnused.setText("unused");

      jRadioButtonUse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
      jRadioButtonUse.setText("use");
      jRadioButtonUse.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButtonUseActionPerformed(evt);
         }
      });

      jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jButtonUpdate.setText("update");
      jButtonUpdate.setActionCommand("Update");

      jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jButtonSearch.setText("search");
      jButtonSearch.setActionCommand("Search");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                  .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jButtonUpdate)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jRadioButtonUnused)
                              .addGap(29, 29, 29)
                              .addComponent(jRadioButtonUse)))
                        .addGap(150, 150, 150))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabelProductName)
                           .addComponent(jLabelProductPrice))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jLabelUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPutId)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldToyId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)
                        .addGap(69, 69, 69))))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabelTitle)
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelPutId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jTextFieldToyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonSearch))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabelProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addGap(1, 1, 1)
                  .addComponent(jTextFieldProductName)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jTextFieldProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jRadioButtonUnused)
               .addComponent(jRadioButtonUse))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButtonUpdate)
            .addGap(20, 20, 20))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void jTextFieldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductNameActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextFieldProductNameActionPerformed

   private void jRadioButtonUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUseActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jRadioButtonUseActionPerformed

   private void jTextFieldToyIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToyIdActionPerformed
      // just enter no click
      // System.out.println(evt.getID());
      // System.out.println(evt.getActionCommand());
   }//GEN-LAST:event_jTextFieldToyIdActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonSearch;
   private javax.swing.JButton jButtonUpdate;
   private javax.swing.JLabel jLabelProductName;
   private javax.swing.JLabel jLabelProductPrice;
   private javax.swing.JLabel jLabelPutId;
   private javax.swing.JLabel jLabelTitle;
   private javax.swing.JLabel jLabelUnit;
   private javax.swing.JRadioButton jRadioButtonUnused;
   private javax.swing.JRadioButton jRadioButtonUse;
   private javax.swing.JTextField jTextFieldProductName;
   private javax.swing.JTextField jTextFieldProductPrice;
   private javax.swing.JTextField jTextFieldToyId;
   // End of variables declaration//GEN-END:variables

   public void display() {
      frame.setContentPane(this);
      frame.setVisible(true);
      
      jButtonSearch.addActionListener(this); 
      jButtonUpdate.addActionListener(this);
      
      frame.addWindowListener(new WindowAdapter() {
         @Override
         public void windowClosing(WindowEvent e) {
            System.out.println("closing this frame");
            toyService.closeConnect();
         }
      });
   }

   @Override
   public void actionPerformed(ActionEvent e) {
      // focus conditions we use e for accessing JButton
      Toy toy = myActionPerformed(e);
      if (toy != null) {
         update(toy);
      }
   }

   private Toy myActionPerformed(ActionEvent actionEvent) {
      if (actionEvent.getActionCommand().equals("Search")) {
         // for showing info that use search
         // connect and query
         toy = toyService.read(Long.valueOf(jTextFieldToyId.getText())); // if not fould it will throw error
         // set toy to each field
         jTextFieldProductName.setText(toy.getProductName());
         jTextFieldProductPrice.setText(toy.getProductPrice().toString());
         String status = toy.getProductStatus().toString();
         
         if (status.equals("use")) {
            jRadioButtonUse.setSelected(true);
         }
         if (status.equals("unused")) {
            jRadioButtonUnused.setSelected(true);
         }
         

      } else if (actionEvent.getActionCommand().equals("Update")) {
         
         toy = new Toy();
         toy.setToyId(Long.valueOf(jTextFieldToyId.getText()));
         toy.setProductName(jTextFieldProductName.getText());
         toy.setProductPrice(Float.valueOf(jTextFieldProductPrice.getText()));
         if (jRadioButtonUnused.isSelected()) {
            toy.setProductStatus(Status.valueOf(jRadioButtonUnused.getText()));
         } else if (jRadioButtonUse.isSelected()) {
            toy.setProductStatus(Status.valueOf(jRadioButtonUse.getText()));
         }
         // then return
         return toy;
      }
      return null;
   }

   private void update(Toy toy) {
      ImageIcon icon;
      Image image;
      Image newimg;
      
      Integer result = toyService.update(toy); // connect and query 
      
      if (result > 0 && result != null) { // used than check
         
         icon = new ImageIcon("src/resources/images/checked.png");
         image = icon.getImage(); // transform it 
         newimg = image.getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
         icon = new ImageIcon(newimg); // transform it back
         JOptionPane.showMessageDialog(this, "updated", "warning", JOptionPane.INFORMATION_MESSAGE, icon);
      
      } else {
         
         icon = new ImageIcon("src/resources/images/remove.png");
         image = icon.getImage(); // transform it 
         newimg = image.getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
         icon = new ImageIcon(newimg); // transform it back
         JOptionPane.showMessageDialog(this, "failed", "warning", JOptionPane.INFORMATION_MESSAGE, icon);
      
      }
      
      // clear value each fileds 
      jTextFieldProductName.setText("");
      jTextFieldProductPrice.setText("");
      jTextFieldToyId.setText("");
      buttonGroupStatus.clearSelection(); // clear all jradio button
   }

}
